name: Build and Zip Extension

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build
    if: "${{ github.event_name != 'push' || startsWith(github.event.head_commit.message, 'chore(release): ') == false }}"
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm exec tsc --noEmit

      - name: Build Chrome
        run: pnpm run build:chrome

      - name: Upload Chrome extension artifacts
        uses: actions/upload-artifact@v4
        with:
          name: quick-copy-ext-chrome
          path: dist_chrome
